### ISSUE TITLE
Enhancement: Support for Swift Package Manager

### ISSUE THREAD

**Issue by Tronicnotes** [getbouncer/cardscan-ios#119]
Is there support for [Swift Package Manager](https://swift.org/package-manager/) available down the pipeline?

**Comment by kingst** [comment]
Yes, for sure. I don't have a concrete date as to when it'll ship, but it's on our radar and something that we will support in the future.

**Comment by brianrjames** [comment]
Seconding the request for Swift Package Manager. It's so much nicer than cocoapods. We've started moving all of our 3rd-party libraries to SPM, when available.

**Comment by pradeep-cash** [comment]
When we can expect SPM support?

**Comment by kingst** [comment]
The main thing that we're waiting for is to have automation in place to test all of our dependency manager support. Once we can test cocoapods and carthage automatically, then we'll add SPM support. Since we're a small team, we try to keep support for this sort of thing to a minimum.

I don't have an exact date for when this support will land, is this a critical feature or something that would be nice to have?

**Comment by kingst** [comment]
We're working on this now -- we plan to have SPM support by the end of the month

**Comment by kingst** [comment]
It's done https://docs.getbouncer.com/card-scan/ios-integration-guide
