### ISSUE TITLE
Expire month and year not read

### ISSUE THREAD

**Issue by tolibovumid** [getbouncer/cardscan-ios#282]
I have use this library to scan my cards. But sometimes library can't read expire month and year. How can I fix it?

**Comment by jaimepark-stripe** [comment]
Hi @tolibovumid!
Our expiration extraction is only supported from iOS 13.0. Is your device iOS 13.0+?

**Comment by tolibovumid** [comment]
Yes. My device iOS version is -14.4.2

**Comment by jaimepark-stripe** [comment]
The scanning loop completion is solely dependent on finding the PAN. This means that there are cases when the expiration is not found quickly enough before the scanning ends. 

One workaround to this problem is configuring the scanning to be `accurate` instead of `fast`. We recommend setting the older devices to `accurate` if you prioritize extracting the expiration. Here is a [link to the doc](https://docs.getbouncer.com/bouncer-scan/credit-card-ocr/ios-integration-guide/advanced-customization#configuration) which will provide more information and instructions on how you can set this up in your project. 

Please let me know if this is helpful. We can dig deeper if the `accurate` option does not work for you.

**Comment by kingst** [comment]
Closing this issue for now, please re-open if you continue to have problems.
